name: shetimitra
description: Shetimitra app
publish_to: 'none'   
version: 1.0.0+1

environment:
  sdk: ^3.5.4

 
dependencies:
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^5.1.0
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.7.3
  shared_preferences: ^2.2.1
  geolocator: ^9.0.0
  connectivity_plus: ^6.1.0
  flutter_local_notifications: ^18.0.0
  image_picker: ^1.1.2

  
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  url_launcher: ^6.0.12
  webview_flutter: ^4.2.1
  intl: ^0.20.1
  flutter_svg: ^2.0.17
  google_maps_flutter: ^2.10.1
  flutter_speed_dial: ^7.0.0
  share_plus: ^10.1.4
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1



flutter_icons:
  android: true
  ios: true
  image_path: "assets/shetimitra.png" 
   
  flutter_lints: ^4.0.0

 
flutter:
  uses-material-design: true

  
  assets:
    - assets/
    - assets/crops/
    - assets/services/
    - assets/images/
    - shorebird.yaml

  